name: flutter_secure_storage_windows
description: Windows implementation of flutter_secure_storage. Please use flutter_secure_storage instead of this package.
repository: https://github.com/mogol/flutter_secure_storage
publish_to: none
version: 4.0.0


environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  ffi: ^2.1.0
  flutter:
    sdk: flutter
  flutter_secure_storage_platform_interface:
    git: https://github.com/kumsumit/flutter_secure_storage_platform_interface.git
  path: ^1.8.3
  path_provider: 
    git: https://github.com/kumsumit/path_provider.git
  win32: ^5.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0

flutter:
  plugin:
    implements: flutter_secure_storage
    platforms:
      windows:
        pluginClass: FlutterSecureStorageWindowsPlugin
        dartPluginClass: FlutterSecureStorageWindows
