name: flutter_secure_storage_windows
description: Windows implementation of flutter_secure_storage. Please use flutter_secure_storage instead of this package.
repository: https://github.com/mogol/flutter_secure_storage
version: 4.2.1
publish_to: none

environment:
  sdk: '>=3.11.0 <4.0.0'
  flutter: '>=3.41.0'

dependencies:
  ffi: ^2.2.0
  flutter:
    sdk: flutter
  flutter_secure_storage_platform_interface:
    git: https://github.com/kumsumit/flutter_secure_storage_platform_interface.git
  path: ^1.9.1
  path_provider:
    git: https://github.com/kumsumit/path_provider.git
  path_provider_platform_interface:
    git: https://github.com/kumsumit/path_provider_platform_interface.git
  win32: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  path_provider_windows:
    git: https://github.com/kumsumit/path_provider_windows.git
  very_good_analysis: ^10.2.0

flutter:
  plugin:
    implements: flutter_secure_storage
    platforms:
      windows:
        pluginClass: FlutterSecureStorageWindowsPlugin
        dartPluginClass: FlutterSecureStorageWindows
